// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using VxTel.Api.Data;

#nullable disable

namespace VxTel.Api.Migrations
{
    [DbContext(typeof(VxTelDbContext))]
    [Migration("20220923203920_ModificadoNomePropriedadeValor")]
    partial class ModificadoNomePropriedadeValor
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("VxTel.Api.Models.Cidade", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CodigoDdd")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Cidades");
                });

            modelBuilder.Entity("VxTel.Api.Models.Plano", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Minutos")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Planos");
                });

            modelBuilder.Entity("VxTel.Api.Models.Tarifa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("IdCidadeDestino")
                        .HasColumnType("int");

                    b.Property<int>("IdCidadeOrigem")
                        .HasColumnType("int");

                    b.Property<float>("Valor")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("IdCidadeDestino");

                    b.HasIndex("IdCidadeOrigem");

                    b.ToTable("Tarifas");
                });

            modelBuilder.Entity("VxTel.Api.Models.Tarifa", b =>
                {
                    b.HasOne("VxTel.Api.Models.Cidade", "CidadeDestino")
                        .WithMany("TarifasComoDestino")
                        .HasForeignKey("IdCidadeDestino")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("VxTel.Api.Models.Cidade", "CidadeOrigem")
                        .WithMany("TarifasComoOrigem")
                        .HasForeignKey("IdCidadeOrigem")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CidadeDestino");

                    b.Navigation("CidadeOrigem");
                });

            modelBuilder.Entity("VxTel.Api.Models.Cidade", b =>
                {
                    b.Navigation("TarifasComoDestino");

                    b.Navigation("TarifasComoOrigem");
                });
#pragma warning restore 612, 618
        }
    }
}
